/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DeviceId = IDL.Nat;
export const Device = IDL.Record({
  'id' : DeviceId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : Timestamp,
});
export const DeviceWithLatestLocation = IDL.Record({
  'device' : Device,
  'latestLocation' : IDL.Opt(Location),
});
export const DeviceWithLocations = IDL.Record({
  'device' : Device,
  'locations' : IDL.Vec(Location),
});

export const idlService = IDL.Service({
  'getAllDevices' : IDL.Func([], [IDL.Vec(Device)], ['query']),
  'getAllDevicesWithLatestLocation' : IDL.Func(
      [],
      [IDL.Vec(DeviceWithLatestLocation)],
      ['query'],
    ),
  'getDeviceWithLocations' : IDL.Func(
      [DeviceId],
      [IDL.Opt(DeviceWithLocations)],
      ['query'],
    ),
  'getLatestLocation' : IDL.Func([DeviceId], [IDL.Opt(Location)], ['query']),
  'getLocationHistory' : IDL.Func([DeviceId], [IDL.Vec(Location)], ['query']),
  'getMyDevices' : IDL.Func([], [IDL.Vec(Device)], ['query']),
  'registerDevice' : IDL.Func([IDL.Text], [DeviceId], []),
  'removeDevice' : IDL.Func([DeviceId], [], []),
  'updateLocation' : IDL.Func([DeviceId, IDL.Float64, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DeviceId = IDL.Nat;
  const Device = IDL.Record({
    'id' : DeviceId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : Timestamp,
  });
  const DeviceWithLatestLocation = IDL.Record({
    'device' : Device,
    'latestLocation' : IDL.Opt(Location),
  });
  const DeviceWithLocations = IDL.Record({
    'device' : Device,
    'locations' : IDL.Vec(Location),
  });
  
  return IDL.Service({
    'getAllDevices' : IDL.Func([], [IDL.Vec(Device)], ['query']),
    'getAllDevicesWithLatestLocation' : IDL.Func(
        [],
        [IDL.Vec(DeviceWithLatestLocation)],
        ['query'],
      ),
    'getDeviceWithLocations' : IDL.Func(
        [DeviceId],
        [IDL.Opt(DeviceWithLocations)],
        ['query'],
      ),
    'getLatestLocation' : IDL.Func([DeviceId], [IDL.Opt(Location)], ['query']),
    'getLocationHistory' : IDL.Func([DeviceId], [IDL.Vec(Location)], ['query']),
    'getMyDevices' : IDL.Func([], [IDL.Vec(Device)], ['query']),
    'registerDevice' : IDL.Func([IDL.Text], [DeviceId], []),
    'removeDevice' : IDL.Func([DeviceId], [], []),
    'updateLocation' : IDL.Func([DeviceId, IDL.Float64, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };