/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Device {
  'id' : DeviceId,
  'owner' : Principal,
  'name' : string,
}
export type DeviceId = bigint;
export interface DeviceWithLatestLocation {
  'device' : Device,
  'latestLocation' : [] | [Location],
}
export interface DeviceWithLocations {
  'device' : Device,
  'locations' : Array<Location>,
}
export interface Location {
  'latitude' : number,
  'longitude' : number,
  'timestamp' : Timestamp,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'getAllDevices' : ActorMethod<[], Array<Device>>,
  'getAllDevicesWithLatestLocation' : ActorMethod<
    [],
    Array<DeviceWithLatestLocation>
  >,
  'getDeviceWithLocations' : ActorMethod<
    [DeviceId],
    [] | [DeviceWithLocations]
  >,
  'getLatestLocation' : ActorMethod<[DeviceId], [] | [Location]>,
  'getLocationHistory' : ActorMethod<[DeviceId], Array<Location>>,
  'getMyDevices' : ActorMethod<[], Array<Device>>,
  'registerDevice' : ActorMethod<[string], DeviceId>,
  'removeDevice' : ActorMethod<[DeviceId], undefined>,
  'updateLocation' : ActorMethod<[DeviceId, number, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];