/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: number;
    longitude: number;
    timestamp: Timestamp;
}
export interface DeviceWithLatestLocation {
    device: Device;
    latestLocation?: Location;
}
export type Timestamp = bigint;
export type DeviceId = bigint;
export interface Device {
    id: DeviceId;
    owner: Principal;
    name: string;
}
export interface DeviceWithLocations {
    device: Device;
    locations: Array<Location>;
}
export interface backendInterface {
    getAllDevices(): Promise<Array<Device>>;
    getAllDevicesWithLatestLocation(): Promise<Array<DeviceWithLatestLocation>>;
    getDeviceWithLocations(deviceId: DeviceId): Promise<DeviceWithLocations | null>;
    getLatestLocation(deviceId: DeviceId): Promise<Location | null>;
    getLocationHistory(deviceId: DeviceId): Promise<Array<Location>>;
    getMyDevices(): Promise<Array<Device>>;
    registerDevice(name: string): Promise<DeviceId>;
    removeDevice(deviceId: DeviceId): Promise<void>;
    updateLocation(deviceId: DeviceId, latitude: number, longitude: number): Promise<void>;
}
import type { Device as _Device, DeviceWithLatestLocation as _DeviceWithLatestLocation, DeviceWithLocations as _DeviceWithLocations, Location as _Location } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllDevices(): Promise<Array<Device>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDevices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDevices();
            return result;
        }
    }
    async getAllDevicesWithLatestLocation(): Promise<Array<DeviceWithLatestLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDevicesWithLatestLocation();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDevicesWithLatestLocation();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeviceWithLocations(arg0: DeviceId): Promise<DeviceWithLocations | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeviceWithLocations(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeviceWithLocations(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestLocation(arg0: DeviceId): Promise<Location | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestLocation(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestLocation(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocationHistory(arg0: DeviceId): Promise<Array<Location>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocationHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocationHistory(arg0);
            return result;
        }
    }
    async getMyDevices(): Promise<Array<Device>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDevices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDevices();
            return result;
        }
    }
    async registerDevice(arg0: string): Promise<DeviceId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDevice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDevice(arg0);
            return result;
        }
    }
    async removeDevice(arg0: DeviceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeDevice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeDevice(arg0);
            return result;
        }
    }
    async updateLocation(arg0: DeviceId, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocation(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_DeviceWithLatestLocation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeviceWithLatestLocation): DeviceWithLatestLocation {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DeviceWithLocations]): DeviceWithLocations | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    device: _Device;
    latestLocation: [] | [_Location];
}): {
    device: Device;
    latestLocation?: Location;
} {
    return {
        device: value.device,
        latestLocation: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.latestLocation))
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DeviceWithLatestLocation>): Array<DeviceWithLatestLocation> {
    return value.map((x)=>from_candid_DeviceWithLatestLocation_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
